global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tempbox'
    static_configs:
      - targets: ['tempbox-service.tempbox.svc.cluster.local:80']
    metrics_path: '/metrics'
