apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "tempbox" }}
  labels:
    app: tempbox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tempbox
  template:
    metadata:
      labels:
        app: tempbox
    spec:
      containers:
      - name: tempbox
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessPath }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessPath }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
