apiVersion: v1
kind: ConfigMap
metadata:
  name: tempbox-config
  namespace: tempbox
data:
  API_TIMEOUT: "10"
  CACHE_TTL: "60"
  SENSEBOX_IDS: "5eba5fbad46fb8001b799786,5c21ff8f919bf8001adf2488,5ade1acf223bd80019a1011c"
