apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempbox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tempbox
  template:
    metadata:
      labels:
        app: tempbox
    spec:
      containers:
      - name: tempbox
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
