apiVersion: v1
kind: Service
metadata:
  name: tempbox-service
spec:
  selector:
    app: tempbox
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
