apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempbox-ingress
  namespace: tempbox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tempbox.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tempbox-service
            port:
              number: 80
